// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocolbuffers/messages.proto

package io.rainbow.commonthread.protocolbuffers;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DeviceOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated bytes id = 1;
    /**
     * <code>repeated bytes id = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getIdList();
    /**
     * <code>repeated bytes id = 1;</code>
     */
    int getIdCount();
    /**
     * <code>repeated bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId(int index);

    // repeated float position = 2;
    /**
     * <code>repeated float position = 2;</code>
     */
    java.util.List<java.lang.Float> getPositionList();
    /**
     * <code>repeated float position = 2;</code>
     */
    int getPositionCount();
    /**
     * <code>repeated float position = 2;</code>
     */
    float getPosition(int index);

    // repeated float orientation = 3;
    /**
     * <code>repeated float orientation = 3;</code>
     */
    java.util.List<java.lang.Float> getOrientationList();
    /**
     * <code>repeated float orientation = 3;</code>
     */
    int getOrientationCount();
    /**
     * <code>repeated float orientation = 3;</code>
     */
    float getOrientation(int index);

    // repeated uint32 sequence = 4;
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    java.util.List<java.lang.Integer> getSequenceList();
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    int getSequenceCount();
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    int getSequence(int index);

    // repeated float interpolation = 5;
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    java.util.List<java.lang.Float> getInterpolationList();
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    int getInterpolationCount();
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    float getInterpolation(int index);

    // repeated float distances = 6;
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    java.util.List<java.lang.Float> getDistancesList();
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    int getDistancesCount();
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    float getDistances(int index);
  }
  /**
   * Protobuf type {@code Device}
   */
  public static final class Device extends
      com.google.protobuf.GeneratedMessageLite
      implements DeviceOrBuilder {
    // Use Device.newBuilder() to construct.
    private Device(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Device(boolean noInit) {}

    private static final Device defaultInstance;
    public static Device getDefaultInstance() {
      return defaultInstance;
    }

    public Device getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Device(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readBytes());
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                position_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              position_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                position_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                position_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                orientation_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              orientation_.add(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                orientation_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                orientation_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                sequence_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              sequence_.add(input.readUInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                sequence_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                sequence_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 45: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                interpolation_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000010;
              }
              interpolation_.add(input.readFloat());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                interpolation_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                interpolation_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 53: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                distances_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000020;
              }
              distances_.add(input.readFloat());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                distances_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                distances_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = java.util.Collections.unmodifiableList(position_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          orientation_ = java.util.Collections.unmodifiableList(orientation_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          sequence_ = java.util.Collections.unmodifiableList(sequence_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          interpolation_ = java.util.Collections.unmodifiableList(interpolation_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          distances_ = java.util.Collections.unmodifiableList(distances_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Device> PARSER =
        new com.google.protobuf.AbstractParser<Device>() {
      public Device parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Device(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Device> getParserForType() {
      return PARSER;
    }

    // repeated bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> id_;
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId(int index) {
      return id_.get(index);
    }

    // repeated float position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> position_;
    /**
     * <code>repeated float position = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getPositionList() {
      return position_;
    }
    /**
     * <code>repeated float position = 2;</code>
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated float position = 2;</code>
     */
    public float getPosition(int index) {
      return position_.get(index);
    }

    // repeated float orientation = 3;
    public static final int ORIENTATION_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Float> orientation_;
    /**
     * <code>repeated float orientation = 3;</code>
     */
    public java.util.List<java.lang.Float>
        getOrientationList() {
      return orientation_;
    }
    /**
     * <code>repeated float orientation = 3;</code>
     */
    public int getOrientationCount() {
      return orientation_.size();
    }
    /**
     * <code>repeated float orientation = 3;</code>
     */
    public float getOrientation(int index) {
      return orientation_.get(index);
    }

    // repeated uint32 sequence = 4;
    public static final int SEQUENCE_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> sequence_;
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getSequenceList() {
      return sequence_;
    }
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    public int getSequenceCount() {
      return sequence_.size();
    }
    /**
     * <code>repeated uint32 sequence = 4;</code>
     */
    public int getSequence(int index) {
      return sequence_.get(index);
    }

    // repeated float interpolation = 5;
    public static final int INTERPOLATION_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Float> interpolation_;
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    public java.util.List<java.lang.Float>
        getInterpolationList() {
      return interpolation_;
    }
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    public int getInterpolationCount() {
      return interpolation_.size();
    }
    /**
     * <code>repeated float interpolation = 5;</code>
     *
     * <pre>
     * corner and control points from previous to next 
     * </pre>
     */
    public float getInterpolation(int index) {
      return interpolation_.get(index);
    }

    // repeated float distances = 6;
    public static final int DISTANCES_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Float> distances_;
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    public java.util.List<java.lang.Float>
        getDistancesList() {
      return distances_;
    }
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    public int getDistancesCount() {
      return distances_.size();
    }
    /**
     * <code>repeated float distances = 6;</code>
     *
     * <pre>
     * spline distances from previous to next (approximate) 
     * </pre>
     */
    public float getDistances(int index) {
      return distances_.get(index);
    }

    private void initFields() {
      id_ = java.util.Collections.emptyList();
      position_ = java.util.Collections.emptyList();
      orientation_ = java.util.Collections.emptyList();
      sequence_ = java.util.Collections.emptyList();
      interpolation_ = java.util.Collections.emptyList();
      distances_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < id_.size(); i++) {
        output.writeBytes(1, id_.get(i));
      }
      for (int i = 0; i < position_.size(); i++) {
        output.writeFloat(2, position_.get(i));
      }
      for (int i = 0; i < orientation_.size(); i++) {
        output.writeFloat(3, orientation_.get(i));
      }
      for (int i = 0; i < sequence_.size(); i++) {
        output.writeUInt32(4, sequence_.get(i));
      }
      for (int i = 0; i < interpolation_.size(); i++) {
        output.writeFloat(5, interpolation_.get(i));
      }
      for (int i = 0; i < distances_.size(); i++) {
        output.writeFloat(6, distances_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(id_.get(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getPositionList().size();
        size += dataSize;
        size += 1 * getPositionList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getOrientationList().size();
        size += dataSize;
        size += 1 * getOrientationList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sequence_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(sequence_.get(i));
        }
        size += dataSize;
        size += 1 * getSequenceList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getInterpolationList().size();
        size += dataSize;
        size += 1 * getInterpolationList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDistancesList().size();
        size += dataSize;
        size += 1 * getDistancesList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.rainbow.commonthread.protocolbuffers.MessageProtos.Device prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Device}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.rainbow.commonthread.protocolbuffers.MessageProtos.Device, Builder>
        implements io.rainbow.commonthread.protocolbuffers.MessageProtos.DeviceOrBuilder {
      // Construct using io.rainbow.commonthread.protocolbuffers.MessageProtos.Device.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        orientation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        sequence_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        interpolation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        distances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Device getDefaultInstanceForType() {
        return io.rainbow.commonthread.protocolbuffers.MessageProtos.Device.getDefaultInstance();
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Device build() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Device result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Device buildPartial() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Device result = new io.rainbow.commonthread.protocolbuffers.MessageProtos.Device(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = java.util.Collections.unmodifiableList(position_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.position_ = position_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          orientation_ = java.util.Collections.unmodifiableList(orientation_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.orientation_ = orientation_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          sequence_ = java.util.Collections.unmodifiableList(sequence_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.sequence_ = sequence_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          interpolation_ = java.util.Collections.unmodifiableList(interpolation_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.interpolation_ = interpolation_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          distances_ = java.util.Collections.unmodifiableList(distances_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.distances_ = distances_;
        return result;
      }

      public Builder mergeFrom(io.rainbow.commonthread.protocolbuffers.MessageProtos.Device other) {
        if (other == io.rainbow.commonthread.protocolbuffers.MessageProtos.Device.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          
        }
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          
        }
        if (!other.orientation_.isEmpty()) {
          if (orientation_.isEmpty()) {
            orientation_ = other.orientation_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOrientationIsMutable();
            orientation_.addAll(other.orientation_);
          }
          
        }
        if (!other.sequence_.isEmpty()) {
          if (sequence_.isEmpty()) {
            sequence_ = other.sequence_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSequenceIsMutable();
            sequence_.addAll(other.sequence_);
          }
          
        }
        if (!other.interpolation_.isEmpty()) {
          if (interpolation_.isEmpty()) {
            interpolation_ = other.interpolation_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureInterpolationIsMutable();
            interpolation_.addAll(other.interpolation_);
          }
          
        }
        if (!other.distances_.isEmpty()) {
          if (distances_.isEmpty()) {
            distances_ = other.distances_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDistancesIsMutable();
            distances_.addAll(other.distances_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Device parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.rainbow.commonthread.protocolbuffers.MessageProtos.Device) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes id = 1;
      private java.util.List<com.google.protobuf.ByteString> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<com.google.protobuf.ByteString>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder setId(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder addId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureIdIsMutable();
        super.addAll(values, id_);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }

      // repeated float position = 2;
      private java.util.List<java.lang.Float> position_ = java.util.Collections.emptyList();
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = new java.util.ArrayList<java.lang.Float>(position_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getPositionList() {
        return java.util.Collections.unmodifiableList(position_);
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public int getPositionCount() {
        return position_.size();
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public float getPosition(int index) {
        return position_.get(index);
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public Builder setPosition(
          int index, float value) {
        ensurePositionIsMutable();
        position_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public Builder addPosition(float value) {
        ensurePositionIsMutable();
        position_.add(value);
        
        return this;
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensurePositionIsMutable();
        super.addAll(values, position_);
        
        return this;
      }
      /**
       * <code>repeated float position = 2;</code>
       */
      public Builder clearPosition() {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }

      // repeated float orientation = 3;
      private java.util.List<java.lang.Float> orientation_ = java.util.Collections.emptyList();
      private void ensureOrientationIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          orientation_ = new java.util.ArrayList<java.lang.Float>(orientation_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public java.util.List<java.lang.Float>
          getOrientationList() {
        return java.util.Collections.unmodifiableList(orientation_);
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public int getOrientationCount() {
        return orientation_.size();
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public float getOrientation(int index) {
        return orientation_.get(index);
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public Builder setOrientation(
          int index, float value) {
        ensureOrientationIsMutable();
        orientation_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public Builder addOrientation(float value) {
        ensureOrientationIsMutable();
        orientation_.add(value);
        
        return this;
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public Builder addAllOrientation(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureOrientationIsMutable();
        super.addAll(values, orientation_);
        
        return this;
      }
      /**
       * <code>repeated float orientation = 3;</code>
       */
      public Builder clearOrientation() {
        orientation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }

      // repeated uint32 sequence = 4;
      private java.util.List<java.lang.Integer> sequence_ = java.util.Collections.emptyList();
      private void ensureSequenceIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          sequence_ = new java.util.ArrayList<java.lang.Integer>(sequence_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getSequenceList() {
        return java.util.Collections.unmodifiableList(sequence_);
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public int getSequenceCount() {
        return sequence_.size();
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public int getSequence(int index) {
        return sequence_.get(index);
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public Builder setSequence(
          int index, int value) {
        ensureSequenceIsMutable();
        sequence_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public Builder addSequence(int value) {
        ensureSequenceIsMutable();
        sequence_.add(value);
        
        return this;
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public Builder addAllSequence(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSequenceIsMutable();
        super.addAll(values, sequence_);
        
        return this;
      }
      /**
       * <code>repeated uint32 sequence = 4;</code>
       */
      public Builder clearSequence() {
        sequence_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        
        return this;
      }

      // repeated float interpolation = 5;
      private java.util.List<java.lang.Float> interpolation_ = java.util.Collections.emptyList();
      private void ensureInterpolationIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          interpolation_ = new java.util.ArrayList<java.lang.Float>(interpolation_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public java.util.List<java.lang.Float>
          getInterpolationList() {
        return java.util.Collections.unmodifiableList(interpolation_);
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public int getInterpolationCount() {
        return interpolation_.size();
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public float getInterpolation(int index) {
        return interpolation_.get(index);
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public Builder setInterpolation(
          int index, float value) {
        ensureInterpolationIsMutable();
        interpolation_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public Builder addInterpolation(float value) {
        ensureInterpolationIsMutable();
        interpolation_.add(value);
        
        return this;
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public Builder addAllInterpolation(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureInterpolationIsMutable();
        super.addAll(values, interpolation_);
        
        return this;
      }
      /**
       * <code>repeated float interpolation = 5;</code>
       *
       * <pre>
       * corner and control points from previous to next 
       * </pre>
       */
      public Builder clearInterpolation() {
        interpolation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }

      // repeated float distances = 6;
      private java.util.List<java.lang.Float> distances_ = java.util.Collections.emptyList();
      private void ensureDistancesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          distances_ = new java.util.ArrayList<java.lang.Float>(distances_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public java.util.List<java.lang.Float>
          getDistancesList() {
        return java.util.Collections.unmodifiableList(distances_);
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public int getDistancesCount() {
        return distances_.size();
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public float getDistances(int index) {
        return distances_.get(index);
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public Builder setDistances(
          int index, float value) {
        ensureDistancesIsMutable();
        distances_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public Builder addDistances(float value) {
        ensureDistancesIsMutable();
        distances_.add(value);
        
        return this;
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public Builder addAllDistances(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDistancesIsMutable();
        super.addAll(values, distances_);
        
        return this;
      }
      /**
       * <code>repeated float distances = 6;</code>
       *
       * <pre>
       * spline distances from previous to next (approximate) 
       * </pre>
       */
      public Builder clearDistances() {
        distances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Device)
    }

    static {
      defaultInstance = new Device(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Device)
  }

  public interface MomentOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated bytes id = 1;
    /**
     * <code>repeated bytes id = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getIdList();
    /**
     * <code>repeated bytes id = 1;</code>
     */
    int getIdCount();
    /**
     * <code>repeated bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId(int index);

    // optional uint64 creation_time = 2;
    /**
     * <code>optional uint64 creation_time = 2;</code>
     */
    boolean hasCreationTime();
    /**
     * <code>optional uint64 creation_time = 2;</code>
     */
    long getCreationTime();

    // repeated bytes data = 3;
    /**
     * <code>repeated bytes data = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDataList();
    /**
     * <code>repeated bytes data = 3;</code>
     */
    int getDataCount();
    /**
     * <code>repeated bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData(int index);

    // optional double sequence = 4;
    /**
     * <code>optional double sequence = 4;</code>
     */
    boolean hasSequence();
    /**
     * <code>optional double sequence = 4;</code>
     */
    double getSequence();

    // optional bool delete = 5;
    /**
     * <code>optional bool delete = 5;</code>
     */
    boolean hasDelete();
    /**
     * <code>optional bool delete = 5;</code>
     */
    boolean getDelete();
  }
  /**
   * Protobuf type {@code Moment}
   */
  public static final class Moment extends
      com.google.protobuf.GeneratedMessageLite
      implements MomentOrBuilder {
    // Use Moment.newBuilder() to construct.
    private Moment(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Moment(boolean noInit) {}

    private static final Moment defaultInstance;
    public static Moment getDefaultInstance() {
      return defaultInstance;
    }

    public Moment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Moment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readBytes());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              creationTime_ = input.readUInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              data_.add(input.readBytes());
              break;
            }
            case 33: {
              bitField0_ |= 0x00000002;
              sequence_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              delete_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Moment> PARSER =
        new com.google.protobuf.AbstractParser<Moment>() {
      public Moment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Moment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Moment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> id_;
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId(int index) {
      return id_.get(index);
    }

    // optional uint64 creation_time = 2;
    public static final int CREATION_TIME_FIELD_NUMBER = 2;
    private long creationTime_;
    /**
     * <code>optional uint64 creation_time = 2;</code>
     */
    public boolean hasCreationTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 creation_time = 2;</code>
     */
    public long getCreationTime() {
      return creationTime_;
    }

    // repeated bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> data_;
    /**
     * <code>repeated bytes data = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bytes data = 3;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }

    // optional double sequence = 4;
    public static final int SEQUENCE_FIELD_NUMBER = 4;
    private double sequence_;
    /**
     * <code>optional double sequence = 4;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double sequence = 4;</code>
     */
    public double getSequence() {
      return sequence_;
    }

    // optional bool delete = 5;
    public static final int DELETE_FIELD_NUMBER = 5;
    private boolean delete_;
    /**
     * <code>optional bool delete = 5;</code>
     */
    public boolean hasDelete() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool delete = 5;</code>
     */
    public boolean getDelete() {
      return delete_;
    }

    private void initFields() {
      id_ = java.util.Collections.emptyList();
      creationTime_ = 0L;
      data_ = java.util.Collections.emptyList();
      sequence_ = 0D;
      delete_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < id_.size(); i++) {
        output.writeBytes(1, id_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(2, creationTime_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(3, data_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(4, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(5, delete_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(id_.get(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, creationTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, delete_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Moment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment, Builder>
        implements io.rainbow.commonthread.protocolbuffers.MessageProtos.MomentOrBuilder {
      // Construct using io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        creationTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        sequence_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        delete_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment getDefaultInstanceForType() {
        return io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment.getDefaultInstance();
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment build() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment buildPartial() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment result = new io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.creationTime_ = creationTime_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.delete_ = delete_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment other) {
        if (other == io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          
        }
        if (other.hasCreationTime()) {
          setCreationTime(other.getCreationTime());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasDelete()) {
          setDelete(other.getDelete());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.rainbow.commonthread.protocolbuffers.MessageProtos.Moment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes id = 1;
      private java.util.List<com.google.protobuf.ByteString> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<com.google.protobuf.ByteString>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder setId(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder addId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureIdIsMutable();
        super.addAll(values, id_);
        
        return this;
      }
      /**
       * <code>repeated bytes id = 1;</code>
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }

      // optional uint64 creation_time = 2;
      private long creationTime_ ;
      /**
       * <code>optional uint64 creation_time = 2;</code>
       */
      public boolean hasCreationTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 creation_time = 2;</code>
       */
      public long getCreationTime() {
        return creationTime_;
      }
      /**
       * <code>optional uint64 creation_time = 2;</code>
       */
      public Builder setCreationTime(long value) {
        bitField0_ |= 0x00000002;
        creationTime_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 creation_time = 2;</code>
       */
      public Builder clearCreationTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        creationTime_ = 0L;
        
        return this;
      }

      // repeated bytes data = 3;
      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }

      // optional double sequence = 4;
      private double sequence_ ;
      /**
       * <code>optional double sequence = 4;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double sequence = 4;</code>
       */
      public double getSequence() {
        return sequence_;
      }
      /**
       * <code>optional double sequence = 4;</code>
       */
      public Builder setSequence(double value) {
        bitField0_ |= 0x00000008;
        sequence_ = value;
        
        return this;
      }
      /**
       * <code>optional double sequence = 4;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sequence_ = 0D;
        
        return this;
      }

      // optional bool delete = 5;
      private boolean delete_ ;
      /**
       * <code>optional bool delete = 5;</code>
       */
      public boolean hasDelete() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool delete = 5;</code>
       */
      public boolean getDelete() {
        return delete_;
      }
      /**
       * <code>optional bool delete = 5;</code>
       */
      public Builder setDelete(boolean value) {
        bitField0_ |= 0x00000010;
        delete_ = value;
        
        return this;
      }
      /**
       * <code>optional bool delete = 5;</code>
       */
      public Builder clearDelete() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delete_ = false;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Moment)
    }

    static {
      defaultInstance = new Moment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Moment)
  }

  public interface SyncOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated bytes ids = 1;
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getIdsList();
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    int getIdsCount();
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    com.google.protobuf.ByteString getIds(int index);

    // repeated uint32 lengths = 2;
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    java.util.List<java.lang.Integer> getLengthsList();
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    int getLengthsCount();
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    int getLengths(int index);
  }
  /**
   * Protobuf type {@code Sync}
   */
  public static final class Sync extends
      com.google.protobuf.GeneratedMessageLite
      implements SyncOrBuilder {
    // Use Sync.newBuilder() to construct.
    private Sync(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Sync(boolean noInit) {}

    private static final Sync defaultInstance;
    public static Sync getDefaultInstance() {
      return defaultInstance;
    }

    public Sync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Sync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ids_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              ids_.add(input.readBytes());
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                lengths_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              lengths_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                lengths_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                lengths_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          lengths_ = java.util.Collections.unmodifiableList(lengths_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Sync> PARSER =
        new com.google.protobuf.AbstractParser<Sync>() {
      public Sync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Sync> getParserForType() {
      return PARSER;
    }

    // repeated bytes ids = 1;
    public static final int IDS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> ids_;
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated bytes ids = 1;</code>
     */
    public com.google.protobuf.ByteString getIds(int index) {
      return ids_.get(index);
    }

    // repeated uint32 lengths = 2;
    public static final int LENGTHS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> lengths_;
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getLengthsList() {
      return lengths_;
    }
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    public int getLengthsCount() {
      return lengths_.size();
    }
    /**
     * <code>repeated uint32 lengths = 2;</code>
     */
    public int getLengths(int index) {
      return lengths_.get(index);
    }

    private void initFields() {
      ids_ = java.util.Collections.emptyList();
      lengths_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ids_.size(); i++) {
        output.writeBytes(1, ids_.get(i));
      }
      for (int i = 0; i < lengths_.size(); i++) {
        output.writeUInt32(2, lengths_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(ids_.get(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lengths_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(lengths_.get(i));
        }
        size += dataSize;
        size += 1 * getLengthsList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Sync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync, Builder>
        implements io.rainbow.commonthread.protocolbuffers.MessageProtos.SyncOrBuilder {
      // Construct using io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        lengths_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync getDefaultInstanceForType() {
        return io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync.getDefaultInstance();
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync build() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync buildPartial() {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync result = new io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          lengths_ = java.util.Collections.unmodifiableList(lengths_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.lengths_ = lengths_;
        return result;
      }

      public Builder mergeFrom(io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync other) {
        if (other == io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          
        }
        if (!other.lengths_.isEmpty()) {
          if (lengths_.isEmpty()) {
            lengths_ = other.lengths_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLengthsIsMutable();
            lengths_.addAll(other.lengths_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.rainbow.commonthread.protocolbuffers.MessageProtos.Sync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes ids = 1;
      private java.util.List<com.google.protobuf.ByteString> ids_ = java.util.Collections.emptyList();
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new java.util.ArrayList<com.google.protobuf.ByteString>(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getIdsList() {
        return java.util.Collections.unmodifiableList(ids_);
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public com.google.protobuf.ByteString getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public Builder setIds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public Builder addIds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        
        return this;
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public Builder addAllIds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureIdsIsMutable();
        super.addAll(values, ids_);
        
        return this;
      }
      /**
       * <code>repeated bytes ids = 1;</code>
       */
      public Builder clearIds() {
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }

      // repeated uint32 lengths = 2;
      private java.util.List<java.lang.Integer> lengths_ = java.util.Collections.emptyList();
      private void ensureLengthsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          lengths_ = new java.util.ArrayList<java.lang.Integer>(lengths_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getLengthsList() {
        return java.util.Collections.unmodifiableList(lengths_);
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public int getLengthsCount() {
        return lengths_.size();
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public int getLengths(int index) {
        return lengths_.get(index);
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public Builder setLengths(
          int index, int value) {
        ensureLengthsIsMutable();
        lengths_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public Builder addLengths(int value) {
        ensureLengthsIsMutable();
        lengths_.add(value);
        
        return this;
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public Builder addAllLengths(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLengthsIsMutable();
        super.addAll(values, lengths_);
        
        return this;
      }
      /**
       * <code>repeated uint32 lengths = 2;</code>
       */
      public Builder clearLengths() {
        lengths_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Sync)
    }

    static {
      defaultInstance = new Sync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Sync)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
